name: Archive Dummy Update

on:
  workflow_dispatch:  # Manual trigger

jobs:
  archive-dummy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository without default credentials
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important: disables the bot token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run archive update
        run: |
          python scripts/archive-update.py

      - name: Commit archived files with PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "corvonj2019@gmail.com"
          git config --global user.name "Corvholio"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/Corvholio/Poketcg-radar.git
          git add data/archive/*.csv
          git commit -m "Archived dummy update for May 25th" || echo "No changes to commit"
          git push origin HEAD:main
